const FETCH_TIMERS_SUCCESS = 'FETCH_TIMERS_SUCCESS'
const TIMER_FAILURE_REQUEST = 'TIMER_FAILURE'
const TIMER_LOADING = 'TIMER_LOADING'
const CHANGE_TIMER = 'CHANGE_TIMER'
const REMOVE_TIMER = 'REMOVE_TIMER'
const TIMER_SAVING = 'TIMER_SAVING'
const ADD_TIMER = 'ADD_TIMER'
const ACTIVATE_TIMER = 'ACTIVATE_TIMER'
const CHANGE_ACTIVE_TIMER = 'CHANGE_ACTIVE_TIMER'
const STOP_ACTIVE_TIMER = 'STOP_ACTIVE_TIMER'

export {
    FETCH_TIMERS_SUCCESS,
    TIMER_LOADING,
    TIMER_FAILURE_REQUEST,
    CHANGE_TIMER,
    REMOVE_TIMER,
    TIMER_SAVING,
    ADD_TIMER,
    ACTIVATE_TIMER,
    CHANGE_ACTIVE_TIMER,
    STOP_ACTIVE_TIMER
}
