const FETCH_TIMERS = 'FETCH_TIMERS'
const TIMER_LOADING = 'TIMER_LOADING'
const CHANGE_TIMER = 'CHANGE_TIMER'
const REMOVE_TIMER = 'REMOVE_TIMER'
const TIMER_SAVING = 'TIMER_SAVING'
const ADD_TIMER = 'ADD_TIMER'

export  {
    FETCH_TIMERS,
    TIMER_LOADING,
    CHANGE_TIMER,
    REMOVE_TIMER,
    TIMER_SAVING,
    ADD_TIMER
}